name: app
description: A client application for your password-store (Unix pass).
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  built_collection:
  built_value:
  dart_pg:
  ffi:
  file_picker:
  flutter_secure_storage:
  go_router:
  openpgp:
  path_provider:
  shared_preferences:
  url_launcher:

dev_dependencies:
  build_runner:
  built_value_generator:
  flutter_launcher_icons:
  flutter_lints:

flutter:
  uses-material-design: true
  assets:
    - assets/cacert.pem

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/icon.png
  adaptive_icon_background: "#20446a"
  adaptive_icon_foreground: assets/icons/adaptive_icon_foreground.png
  remove_alpha_ios: true
